name: Build

on:
  workflow_dispatch:
    
jobs:
  build-and-release:
    runs-on: [windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version
      id: package_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: WindowsActivator.csproj
      
    - name: Show
      run: |
          echo v${{ steps.test.package_version.version }}

      
   
      
