name: Build

on:
  workflow_dispatch:
    
jobs:
  build-and-release:
    runs-on: [windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version
    
    - id: make_version_string
      uses: sandersaares-actions/make-version-string@master
      with:
        assemblyInfoPath: Properties/AssemblyInfo.cs
      
    - name: Show
      run: |
          echo v${{ steps.make_version_string.outputs.versionstring }}

      
   
      
